<config>
    <resolveTypedefs>true</resolveTypedefs>
    <qtMode>true</qtMode>
    <generator>smoke</generator>
    <definesList>@QTDEFINES_FILE@</definesList>
    <includeDirs>
        <dir>@Qt5Core_INCLUDE_DIRS@</dir>
    </includeDirs>
</config>
